### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by KeeperOfMaps** [CosmoQuestX/CSB7.0#103]
We should come up with a customized 404 page for the site.

**Comment by dpi209** [comment]
Can you elaborate on that?

**Comment by KeeperOfMaps** [comment]
Right now, it's the generic Apache 404 page. We could create a 404 page that has the look and feel of the main site and provides more useful information on it, while still conveying the message that the page requested doesn't exist.

**Comment by dpi209** [comment]
The security point of view concerns basic Apache HTTPS configuration. 

We can make them prettier by adding ErrorDocuments to the .htaccess, but since we're defininig it on the /csb/ level it would need to move up one directory to cover anythinge else (like calling /csc/ for example). This might collide with other installations, such as Wordpress.

**Comment by KeeperOfMaps** [comment]
It shouldn't collide with WordPress if they're running on different hostnames. If they're on the same hostname, it becomes a little more challenging, but shouldn't be insurmountable.

**Comment by dpi209** [comment]
If they're on the same hostname we should not overwrite an existing .htaccess.

**Comment by KeeperOfMaps** [comment]
True. We can provide one and discuss it in the installation instructions.

**Comment by dpi209** [comment]
Addressed in #111 and added text to Readme.md to clarify
