### ISSUE TITLE
If database fail in installer, delete csb-settings.php that was just created, or write file after DB check

### ISSUE THREAD

**Issue by starstryder** [CosmoQuestX/CSB7.0#27]
Currently, it writes the csb-settings.php file, and THEN checks if DB works. If it doesn't, your stuck having to delete stupid file.

BETTER: Check if DB works, THEN write settings file.

**Comment by dpi209** [comment]
I implemented the delete csb-settings.php part and am adding it to the last PR (because, if something in the middle of creating tables fails, it would still be useful) but I think @eladavron is working on a db connect test for the installer, which would be a much more elegant solution for errors before writing config, especially when making a test mandatory before unlocking the "write config" button.
