### ISSUE TITLE
Favicon needed

### ISSUE THREAD

**Issue by KeeperOfMaps** [CosmoQuestX/CSB7.0#97]
a favicon for the site is needed.

Initially, add just the CQX and in the future make it part of the setup process.

**Comment by TheRealFakeAdmin** [comment]
@KeeperOfMaps There is a [favicon.ico](/CosmoQuestX/CSB7.0/blob/master/csb/favicon.ico) located in the csb directory. Maybe this is an issue with the Apache config?

**Comment by KeeperOfMaps** [comment]
> @KeeperOfMaps There is a [favicon.ico](/CosmoQuestX/CSB7.0/blob/master/csb/favicon.ico) located in the csb directory. Maybe this is an issue with the Apache config?

I just checked my browser and it appears to have the favicon in the titlebar:
![Screen Shot 2022-08-12 at 8 42 07 PM](https://user-images.githubusercontent.com/110957686/184460933-a8fce2cd-2728-4698-8077-cfe5b60ec7bb.png)

So, I'm not sure there's a problem here. Can you check again and if it's still happening post info about your browser, etc. Thanks!

**Comment by TheRealFakeAdmin** [comment]
> So, I'm not sure there's a problem here. Can you check again and if it's still happening post info about your browser, etc.

### Tests
I have tested on Chromium, Firefox, Firefox Developer Edition, & Firefox for ios.

- Chromium does not show any requests for a favicon, and I did not find a link reference for it.
- Firefox & Firefox Dev call for [/favicon.ico](https://sandbox.cosmoquest.org/favicon.ico), returning a `404 Error`
  - This is a Firefox default, not a CSB issue (see `resource:///modules/FaviconLoader.jsm:186:20` on Firefox)
- Firefox ios (running on webKit) did return a favicon, I'm guessing it has an if in `/` else `./` by default

*I was unable to test on any version of Safari, although Safari does run on webKit*

### Possible Reason
The issue could be the favicon is not being called, and since many developers use the Safari browser, it is not noticed (@KeeperOfMaps).

### Proposed Solution
Add `<link rel="icon" type="image/x-icon" href="/csb/favicon.ico">` to the necessary files.
